### ISSUE TITLE
Package Microsoft.Azure.WebJobs.Extensions.CosmosDB v3.0.7 takes dependency on package with criticial issues

### ISSUE THREAD

**Issue by mkowalskigps** [Azure/azure-webjobs-sdk-extensions#647]
The `3.0.7` version of the `Microsoft.Azure.WebJobs.Extensions.CosmosDB` package takes a dependency on `Microsoft.Azure.DocumentDB.Core` version `2.9.2` - based on the issue [here](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/757) there are bugs within that release that cause the same problems to occur downstream.

#### Repro steps
Upgrade package `Microsoft.Azure.WebJobs.Extensions.CosmosDB` to version `3.0.7`

#### Expected behavior
Upstream `Microsoft.Azure.DocumentDB.Core` package does not contain critical bug(s)

#### Actual behavior
Upstream `Microsoft.Azure.DocumentDB.Core` package contains critical bug(s)

#### Known workarounds
Downgrade `Microsoft.Azure.WebJobs.Extensions.CosmosDB` package to `3.0.5` or modify all affected queries to explicitly specify partition key as part of the filter clause

#### Related information 
Package version: `3.0.7`
Related commit: [8f45bd7f0f59a1c29f4d15e25c96fdbfe6ec1b27](https://github.com/Azure/azure-webjobs-sdk-extensions/commit/8f45bd7f0f59a1c29f4d15e25c96fdbfe6ec1b27#diff-4f2fb5274d822ad19d184f4501b3a830R21)

**Comment by mkowalskigps** [comment]
This does appear to be corrected in [this](https://github.com/Azure/azure-webjobs-sdk-extensions/commit/965e66bf1bdd0ad22c63142c80ac65345e05b09f) commit, but this code has not been released yet.

**Comment by fabiocav** [comment]
@yojagad this has since been released, correct?

**Comment by yojagad** [comment]
Yes, It looks to have been released as part of Microsoft.Azure.WebJobs.Extensions 4.0.1

**Comment by techfg** [comment]
@yojagad - Microsoft.Azure.WebJobs.Extensions.CosmosDB is still at 3.0.7 in Nuget so it doesn't appear that the [commit](https://github.com/Azure/azure-webjobs-sdk-extensions/commit/965e66bf1bdd0ad22c63142c80ac65345e05b09f) that @mkowalskigps referenced has been published yet.  I'm still seeing these issues (e.g. [PartitionKey not honored](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/757)) using Microsoft.Azure.WebJobs.Extensions 4.0.1.  

Is there a timeframe on when a new push of Microsoft.Azure.WebJobs.Extensions.CosmosDB will occur so we can move past these issues?

Thank you!

**Comment by shibayan** [comment]
I also believe that this problem has not been solved because the NuGet package has not been published.

The referenced Cosmos DB package is a much older version by now, so hopefully it will be upgraded to the latest compatible version. This is especially important for `ChangeFeedProcessor` because it has built-in compatibility with the latest version of the v3 SDK.

**Comment by ealsur** [comment]
3.0.8 release has been updated with the latest SDK and CFP versions, ETA should be 24-48hs

**Comment by techfg** [comment]
@ealsur - Confirmed 3.0.8 resolves the issues related to 3.0.7 taking the dependency on `Microsoft.Azure.DocumentDB.Core 2.9.2`.  Thank you!
